name: kaito
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  soundpool: ^2.3.0
  cloud_firestore: ^3.4.5
  firebase_auth: ^3.3.20
  url_launcher: ^6.1.6
  firebase_core: ^1.21.0
  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.1
  android_intent_plus: ^3.1.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  image_path: "assets/images/background_logo.png"
  adaptive_icon_background: "#222647"
  adaptive_icon_foreground: "assets/images/background_logo.png"







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/logo.png
    - assets/images/Untitled-1.png
    - assets/images/icons8-private-64.png
    - assets/images/test_avatar.png
    - assets/images/win_count.png
    - assets/images/join_room.png
    - assets/images/create_room.png
    - assets/images/arrow_back.png
    - assets/sounds/on_click_button.mp3
    - assets/sounds/back_ground_room.mp3
    - assets/sounds/game_start.mp3

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: com
      fonts:
        - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/comfortaa/Comfortaa-SemiBold.ttf
          weight: 600


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
